### ISSUE TITLE
Deploy on Heuroku

### ISSUE THREAD

**Issue by ejaquezcastillo** [StartBootstrap/pro-feedback#8]
2020-04-11T15:36:50.167361+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
2020-04-11T15:36:50.167361+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
2020-04-11T15:36:50.167362+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
2020-04-11T15:36:50.167362+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
2020-04-11T15:36:50.167362+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
2020-04-11T15:36:50.167362+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2020-04-11T15:36:50.167362+00:00 app[web.1]:   requireStack: [ '/app/scripts/start.js' ]
2020-04-11T15:36:50.167363+00:00 app[web.1]: }
2020-04-11T15:54:27.348783+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pasaporterd.herokuapp.com request_id=8486f9a0-e6a0-4d25-b6b7-830bf8c395af fwd="98.15.49.238" dyno= connect= service= status=503 bytes= protocol=https
2020-04-11T15:54:27.819632+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=pasaporterd.herokuapp.com request_id=949abc9d-59cc-4c72-b9cf-2fe76d3793bf fwd="98.15.49.238" dyno= connect= service= status=503 bytes= protocol=https

**Comment by initplatform** [comment]
You'll have to provide a little more context, but looking at that log sounds like the app is crashing because there is no favicon?

All of our pro products provide a default favicon.png

**Comment by davidtmiller** [comment]
Closing this one out due to inactivity.
